# Generated by Django 4.1 on 2022-08-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivefile',
            name='fileName',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
