# Generated by Django 4.1 on 2022-08-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_alter_drivefile_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivefile',
            name='fileName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
