# Generated by Django 4.1 on 2022-08-31 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0004_alter_drivefile_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivefile',
            name='fileName',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
