# Generated by Django 4.1 on 2022-08-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0005_alter_drivefile_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivefile',
            name='fileName',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
